name: Semgrep Scan

on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: '0 0 * * 1'  # optional: runs every Monday

jobs:
  semgrep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: returntocorp/semgrep-action@v1
        with:
          config: "p/ci"  # use "auto" or your custom ruleset
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}  # optional for dashboard/reporting
