name: Semgrep Scan

on:
  workflow_dispatch:  # allows manual trigger from GitHub UI
  push:
    branches: [main]
  pull_request:

jobs:
  semgrep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: returntocorp/semgrep-action@v1
        with:
          config: "p/ci"  # use "auto" or your custom ruleset
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}  # optional
